from typing import Dict, List, Set, Tuple, Optional, Any
from collections import defaultdict

class CandidatePool:
    """
    Manages the multi-block candidate pool for query entities.
    Tracks candidate target IDs, deduplication, and strategy provenance.
    """
    def __init__(self):
        # s1_id -> target_id -> set of strategy names
        self.pool: Dict[str, Dict[str, Set[str]]] = defaultdict(lambda: defaultdict(set))

    def add_candidate(self, s1_id: str, target_id: str, strategy: str):
        """Adds a candidate target entity for an S1 query entity."""
        self.pool[s1_id][target_id].add(strategy)

    def add_candidates_batch(
        self,
        s1_id: str,
        candidates_with_provenance: Dict[str, Set[str]]
    ):
        """Adds multiple candidates with their strategy provenance."""
        s1_entry = self.pool[s1_id]
        for tid, strats in candidates_with_provenance.items():
            s1_entry[tid].update(strats)

    def get_candidate_ids(self, s1_id: str) -> Set[str]:
        """Returns the deduplicated set of candidate target IDs for an S1 entity."""
        if s1_id not in self.pool:
            return set()
        return set(self.pool[s1_id].keys())

    def get_provenance(self, s1_id: str, target_id: str) -> Set[str]:
        """Returns the set of strategies that retrieved target_id for s1_id."""
        return self.pool.get(s1_id, {}).get(target_id, set())

    def to_candidate_dict(self) -> Dict[str, Set[str]]:
        """Converts the pool into standard {s1_id: set(target_ids)} format."""
        return {s1: set(targets.keys()) for s1, targets in self.pool.items()}

    def get_strategy_contribution_counts(self) -> Dict[str, int]:
        """Diagnostic count of pairs generated by each strategy."""
        counts = defaultdict(int)
        for s1, targets in self.pool.items():
            for tid, strats in targets.items():
                for s in strats:
                    counts[s] += 1
        return dict(counts)

    def __len__(self) -> int:
        return len(self.pool)
